name: CI
on: [push]
jobs:
  build_manual:
    runs-on: ubuntu-latest
    container:
      image: "debian:latest"
      options: --privileged
    steps:
      - uses: actions/checkout@v1
      - run: apt-get update && apt-get install sudo live-build
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1
